version: '3.2'
services:
  profit-trailer:
    build:
      context: ./profit-trailer
      dockerfile: Dockerfile
      args:
        PT_VERSION: 2.1.10
    ports:
      - '8081:8081'
    networks:
      ptnet:
        aliases: 
          - profit-trailer
    restart: always
    volumes:
      - ./container/pt/config:/var/opt/pt/config
      - ./container/pt/data:/var/opt/pt/data
  pt-feeder:
    build:
      context: ./pt-feeder/
      dockerfile: Dockerfile
      args:
        PTF_VERSION: 1.7.0.1252
    depends_on:
      - profit-trailer
    networks:
      ptnet:
        aliases:
          - pt-feeder
    restart: always
    volumes:
      - ./container/pt/config:/var/opt/pt/config
      - ./container/ptf/config:/var/opt/ptf/config
      - ./container/ptf/database:/var/opt/ptf/database
  
volumes:
  ptc:

networks:
  ptnet: